name: Python Build

on:
  push:
    paths:
    - 'python/**'
    - '.github/workflows/python_test.yml'
  pull_request:
    paths:
    - 'python/**'
    - '.github/workflows/python_test.yml'
  workflow_dispatch:

jobs:
  Install-Test:
    name: Installation test for python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y swig bash mingw-w64
      - name: Install dependencies for macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install swig mingw-w64 bash
      - name: Install dependencies for windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install swig mingw git
      - name: Install abess
        run: |
          python --version
          cd ./python
          python setup.py install
