name: R docs

on:
  push:
    paths:
    - 'R-package/*'
    - '.github/workflow/r_website.yml'
  pull_request:
    paths:
    - 'R-package/*'
    - '.github/workflow/r_website.yml'

jobs:
  pkgdown:
    name: pkgdown
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.ABESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps("R-package", dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps("R-package", dependencies = TRUE)
          install.packages("pkgdown", type = "binary")
          install.packages("survival", type = "binary")
          install.packages("Hmisc", type = "binary")
          install.packages("ROCR", type = "binary")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL R-package

      - name: Deploy package
        run: |
          git config --local user.email "zhuj37@mail2.sysu.edu.cn"
          git config --local user.name "Mamba413"
          Rscript -e 'pkgdown::deploy_to_branch("./R-package", new_process = FALSE, clean = TRUE)'
